### ISSUE TITLE
Refactor pycmo to handle both premium and Steam editions of Command

### ISSUE THREAD

**Issue by duyminh1998** [duyminh1998/pycmo#12]
### We should
refactor `pycmo` to handle both Premium and Steam editions of Command

### Because
currently `pycmo` are written to be only compatible with the premium edition of Command, which requires an expensive license to which many users do not have access

### Complexity
Medium to hard. We can proceed in two phases of work. First, we can refactor the current codebase and note pieces of code that are exclusive to the premium edition of the game. We can then add the codebase to support the Steam edition of the game.

### Definition of Done
Users are able to specify and use `pycmo` for both the premium and Steam editions of Command. More emphasis will be placed on the latter because we do not have access to the premium version of the game (and this codebase has already been developed previously).

**Comment by XiaoFanTong** [comment]
BTW, where  is CPE.ini

**Comment by duyminh1998** [comment]
It has been a while so I do not remember. Check for a `Config` folder. This could be in your `Command` installation folder in `Program Files` or `ProgramData`.

**Comment by XiaoFanTong** [comment]
> It has been a while so I do not remember. Check for a `Config` folder. This could be in your `Command` installation folder in `Program Files` or `ProgramData`. Note that `CPE.ini` is only present in the Premium edition of the game.

I do not find CPE.ini in the Steam editions of Command, so how can I handle Steam editions of Command with pycmo?

**Comment by duyminh1998** [comment]
> > It has been a while so I do not remember. Check for a `Config` folder. This could be in your `Command` installation folder in `Program Files` or `ProgramData`. Note that `CPE.ini` is only present in the Premium edition of the game.
> 
> I do not find CPE.ini in the Steam editions of Command, so how can I handle Steam editions of Command with pycmo?

Getting `pycmo` to work with the Steam version is ongoing work and the purpose for this issue. You can check out a demo by following these [instructions](https://github.com/duyminh1998/pycmo#run-an-agent-steam-edition-only).

**Comment by XiaoFanTong** [comment]
> > > It has been a while so I do not remember. Check for a `Config` folder. This could be in your `Command` installation folder in `Program Files` or `ProgramData`. Note that `CPE.ini` is only present in the Premium edition of the game.
> > 
> > 
> > I do not find CPE.ini in the Steam editions of Command, so how can I handle Steam editions of Command with pycmo?
> 
> Getting `pycmo` to work with the Steam version is ongoing work and the purpose for this issue. You can check out a demo by following these [instructions](https://github.com/duyminh1998/pycmo#run-an-agent-steam-edition-only).

The demo runs successfully.  Good job！

**Comment by duyminh1998** [comment]
Places to refactor:
- `lib/actions.py`
- `lib/features.py`
- `lib/protocol.py`
- `lib/run_loop.py`
- `lib/start_server.py`
- `env/ecmo_env.py`

**Comment by duyminh1998** [comment]
Currently blocked by this [issue](https://github.com/duyminh1998/pycmo/issues/13) in an attempt to focus the work

**Comment by duyminh1998** [comment]
Closed by this [MR](https://github.com/duyminh1998/pycmo/pull/15)
