### ISSUE TITLE
NeuralNetworkAgent status

### ISSUE THREAD

**Issue by johnrachwan123** [duyminh1998/pycmo#3]
Hello,

First of all I would like to thank you for sharing your very interesting work! I would like to ask whether development on the NeuralNetworkAgent is still in progress or its abandonned. 

Thanks!

**Comment by duyminh1998** [comment]
John,

Thank you for your interest in the project. The development of the neural network agent is still in progress. I am planning to finish it as part of my graduate school studies. Estimated time of completion is Summer to Fall of 2022.

Minh

**Comment by johnrachwan123** [comment]
Thanks for your response! Will you be continuously updating the repository as you go through it, or do you plan on pushing at the end of your studies?

**Comment by duyminh1998** [comment]
John,

Thank you for your continued interest. Currently, I plan on updating the repository in May - June of this year. This update will probably involve tidying up the environment code and developing a preliminary model of the Neural Network agent. That is a definite goal I am setting for myself. However, if I find myself having time or learning something applicable between now and May then I will update the repository as needed.

Minh
