### ISSUE TITLE
ScenEdit_ExportScenarioToXML

### ISSUE THREAD

**Issue by psyma** [duyminh1998/pycmo#64]
Hi,

Thank you for your amazing library!

I have a question regarding your ScenEdit_ExportScenarioToXML. Is the output of this function the same as that of the premium edition? If not, how can I modify ScenEdit_ExportScenarioToXML to include additional data from the scene?

Thanks!

**Comment by duyminh1998** [comment]
@psyma thanks for your interest. The function is not the same as the premium edition (in fact, I made a comment in the function's definition that it is only meant to emulate the premium edition's function of the same name). You can modify the function at https://github.com/duyminh1998/pycmo/blob/main/lua/pycmo_lib.lua#L13. The code should automatically pickup whatever is modified in the file (no further installs needed). Let me know if you need further explanations on how the function works.

**Comment by psyma** [comment]
@duyminh1998 I was hoping to replicate the ScenEdit_ExportScenarioToXML from the premium edition. Do you have a sample output?

**Comment by duyminh1998** [comment]
@psyma  any one of the xml files in this folder would be a good bet: https://github.com/duyminh1998/pycmo/tree/main/xml

**Comment by psyma** [comment]
@duyminh1998 thanks a lot
