### ISSUE TITLE
Error in ScenEdit_ExportInst function

### ISSUE THREAD

**Issue by hasantahabagci** [duyminh1998/pycmo#65]
Hello,

While I'm running ScenEdit_ExportInst function in CMO lua editor I got an error: `ScenEdit_ExportInst 0: ,no filename key defined`.

I tried various of scripts but I could not run successfully. Other functions can run properly. In official website there is an example script:

```
ScenEdit_ExportInst('Russia', {'c1a0e312-9ccc-43d1-9e6c-01899c8433d9'}, {filename='ssbn_patrol.inst',name='SSBN on Patrol',comment='Russian SSBN on patrol in Barents'})
```

I tried this one also but did not work. Error says filename key not defined but I defined it as in example. How can I solve this problem? My CMO version is **1.06 - Build v1328.14** and Lua version is 5.4

I need help to solve this. Thanks in advance

**Comment by duyminh1998** [comment]
The following function works for me in the base standalone scenario "A Hunting We Will Go, 1963":

```
ScenEdit_ExportInst('NATO', {'e945f798-60c3-498f-8e6e-b100996b2c0e'}, {filename='ssbn_patrol.inst',name='SSBN on Patrol',comment='Russian SSBN on patrol in Barents'})
```

It outputs the .inst file to the `ImportExport` directory in the game's installation directory. I am using the latest version of the software (from Steam).

Check that the GUID of the unit you are exporting is correct. If all else fails post the scenario you are working with and the command you are trying to run.

FYI if you have questions about the game's built-in Lua functions then the [official Matrix forums](https://www.matrixgames.com/forums/) is a good resource.

**Comment by hasantahabagci** [comment]
I tried as yours but again I got same error. Most probably there is an issue about my version. I also created post in matrix game forum. Is there any alternative to save xml file to use PyCMO? I saw different file operations in Lua language but did not work I could not use them (e.g. `io.open`). Thank you for your help.

**Comment by duyminh1998** [comment]
Is there a reason why you cannot update the game to the most recent version? In my recent test I was using the most recent version of the game available on Steam. I am assuming you do not have the professional edition of the game, which has the easy way to export data (i.e. `ScenEdit_ExportScenarioToXML`). I think `ScenEdit_ExportInst` was my "hack" to get data export working with the non-professional edition of the game.  I looked at the Lua docs again and I do not think there are any other clever workarounds.

**Comment by hasantahabagci** [comment]
I am not able to update game because of Steam application. I found a solution for this issue, getting the observations with different method. Thanks for your help.
