### ISSUE TITLE
Requied license

### ISSUE THREAD

**Issue by chanyeolyoo** [duyminh1998/pycmo#7]
Hi,

First of all, thanks for sharing the code in Github. Before I purchase the game and try out your code, I would like to ask a question.

In the config file, you used the Professional edition. Is this required? I wonder if Steam edition is also supported. 

Thanks.

**Comment by duyminh1998** [comment]
Hi Chanyeol,

The Professional edition is required for several reasons:
1. You need the Lua function [ScenEdit_ExportScenarioToXML()](https://commandlua.github.io/#ScenEdit_ExportScenarioToXML) to output observations. The only alternative is to write your own Lua script and output data using the `io` module, but this might be cumbersome.
2. I actually do not remember if you can use the `io` module in the non-Premium version. You should try it out in the console, but I believe the answer is no. Without `io` or some of the features from the Premium version, you cannot send commands (actions) into the game to take actions.
3. Currently we send actions to the environment/game using a TCP/IP port, a feature only available in the Premium version.

Hope this helps.

Minh

**Comment by duyminh1998** [comment]
Investigating this issue for continued work.

**Comment by duyminh1998** [comment]
Closing this issue to continue work in related [issue](https://github.com/duyminh1998/pycmo/issues/10).

**Comment by duyminh1998** [comment]
Closing this issue to continue work on related [issue](https://github.com/duyminh1998/pycmo/issues/10).
